# Generated by Django 4.0.3 on 2022-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmusica', '0008_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
